version: 2.1
jobs:
  build:
    docker:
      - image: codedarigan/godot32

    steps:
        - checkout
        - run: 
            name: "Run All"
            command: RunAllTests
        - run:
            name: "Run Unit Tests"
            command: godot -s addons/WAT/CLI.gd -run_dir=res://tests/Bootstrapping/Unit
        - run:
            name: "Run Script Director"
            command: godot -s addons/WAT/CLI.gd -run_script=res://tests/Bootstrapping/Integration/script_director.test.gd
        - run:
            name: "Run Scene Director"
            command: godot -s addons/WAT/CLI.gd -run_script=res://tests/Bootstrapping/Integration/scene_director.test.gd
        - run:
            name: "Run Test Doubles"
            command: godot -s addons/WAT/CLI.gd -run_script=res://tests/Bootstrapping/Integration/test_double.test.gd
        - run:
            name: "Run End-To-End Tests"
            command: godot -s addons/WAT/CLI.gd -run_dir=res://tests/Bootstrapping/End2End

commands:
    RunAllTests:
        steps: 
          - run: -godot -s addons/WAT/CLI.gd -run_all
