version: 2.1
jobs:
  build:
    docker:
      - image: codedarigan/godot32

    steps:
        - checkout
        - run:
            name: "Run All Tests"
            command: godot -s addons/WAT/cli.gd -run_all
        - run:
            name: "Run Unit Tests"
            command: godot -s addons/WAT/cli.gd -run_dir=res://tests/Bootstrapping/Unit
        - run:
            name: "Run Integration Tests"
            command: godot -s addons/WAT/cli.gd -run_dir=res://tests/Bootstrapping/Integration
        - run:
            name: "Run End-To-End Tests"
            command: godot -s addons/WAT/cli.gd -run_dir=res://tests/Bootstrapping/End2End
