version: 2.1

jobs:
  build:
    docker:
      - image: codedarigan/wat_godot_3.2rc2

    steps:
        - checkout
        - run:
            name: "Run Unit Tests"
            command: godot addons/WAT/cli.tscn -run_dir=res://tests/unit
        - run:
            name: "Run Integration Tests"
            command: godot addons/WAT/cli.tscn -run_dir=res://tests/integration
        - run:
            name: "Run End-To-End Tests"
            command: godot addons/WAT/cli.tscn -run_dir=res://tests/end_to_end
        - run:
            name: "Run All Tests"
            command: godot addons/WAT/cli.tscn -run_all
