version: 2.1
jobs:
  build:
    docker:
      - image: barichello/godot-ci:3.1.1

    steps:
        - checkout
        - run:
            name: "Run Unit Tests"
            command: godot -s addons/WAT/CLI.gd -run_dir=res://tests/Bootstrapping/Unit
        - run:
            name: "Run Integration Tests"
            command: godot -d -s addons/WAT/CLI.gd -run_script=res://tests/Bootstrapping/Integration
        - run:
            name: "Run End-To-End Tests"
            command: godot -s addons/WAT/CLI.gd -run_dir=res://tests/Bootstrapping/End2End
