
name: CI

on: push

jobs:
  Tests:
    name: Run All Tests
    runs-on:  ubuntu-latest
    container: codedarigan/godot_headless_ci:latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Run
        run: godot addons/WAT/cli.tscn -run_all
        
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: tests/results.xml
