
name: CI

on: push

jobs:
  Tests:
    name: Run All Tests
    runs-on:  ubuntu-latest
    container: barichello/godot-ci:3.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run
        run: godot addons/WAT/cli.tscn -run_all
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: tests/results.xml
